# Generated by Django 3.1.2 on 2021-04-01 07:11

from django.db import migrations, models
import django.db.models.deletion
import src.models.respuestas


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuestionario', models.CharField(max_length=200)),
                ('fecha_aplicacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pregunta', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('es_control', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_respuestas', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_resultados', models.CharField(max_length=200)),
                ('tiempo_respuesta', models.DateTimeField()),
                ('id_cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.cuestionarios')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.preguntas')),
                ('id_respuesta', models.ForeignKey(on_delete=src.models.respuestas.Respuestas, to='models.respuestas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('a_paterno', models.CharField(max_length=200)),
                ('a_materno', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('sexo', models.BooleanField(default=False)),
                ('navegador', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tracking', models.CharField(max_length=200)),
                ('x_axis', models.DecimalField(decimal_places=6, max_digits=7)),
                ('y_axis', models.DecimalField(decimal_places=6, max_digits=7)),
                ('no_movimiento', models.IntegerField()),
                ('hora', models.TimeField()),
                ('id_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.resultados')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaCuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pregunta_cuestionario', models.CharField(max_length=200)),
                ('orden', models.SmallIntegerField()),
                ('id_cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.cuestionarios')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.preguntas')),
            ],
        ),
        migrations.AddField(
            model_name='cuestionarios',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.usuarios'),
        ),
    ]
